blank_issues_enabled: true
contact_links:
  - name: Questions & Discussion
    url: https://github.com/Dimitrios-Kafetzis/EdgeNN/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
